### ISSUE TITLE
pytorch_model.bin is not downloadable from hugging face GanjinZero/UMLSBert_ENG

### ISSUE THREAD

**Issue by MaryFllh** [GanjinZero/CODER#2]
I am trying to save UMLSBert_ENG on my machine but clicking the download icon https://huggingface.co/GanjinZero/UMLSBert_ENG/tree/main does not download the binary file and instead downloads an archive folder with data.pkl and a data folder. 

Please kindly assist.

**Comment by GanjinZero** [comment]
Please just rename the zip file into _pytorch_model.bin_

**Comment by MaryFllh** [comment]
Thank you very much. It works after renaming the folder.
