### ISSUE TITLE
coder++

### ISSUE THREAD

**Issue by 779257747** [GanjinZero/CODER#8]
您好，我了解到您一直在做生物编码这一块，在您的issue中看到您提到您新的研究coder++，是在这个研究的基础上做了一些改进，但是我没有找到相关的论文和github链接，如果方便请您告知一下，感谢！

**Comment by GanjinZero** [comment]
https://arxiv.org/abs/2204.00391

**Comment by GanjinZero** [comment]
github就在这里有个coderpp的文件夹

**Comment by 779257747** [comment]
想问一下coderpp也是对生物医学实体做编码的吗，也可以用来做相似度计算的

**Comment by GanjinZero** [comment]
是的
